/******************************************************
 * Stage module implementation file.                  *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/

#include "msp430_pipe_EX.H"

inline void msp430_pipe_EX::msp430_pipe_EX::behavior()
{
 unsigned ins_id;
 ac_instr_t* instr_vec;

 if (ac_stop_flag)
  return;
 if (is_stalled())
  ctrl.request_update();
 instr_vec = new ac_instr_t(regin->read());
 ins_id = instr_vec->get(IDENT);
 if (ins_id != 0)
 {
  isa.current_instruction_id = ins_id;
  isa._behavior_instruction(static_cast<msp430_parms::ac_stage_list>(id), 0);
  switch (ins_id)
  {
   case 1: // mov_48imm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_mov_48imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 2: // mov_48idm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_mov_48idm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 3: // add_48idm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_add_48idm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 4: // add_48imm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_add_48imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 5: // addc_48idm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_addc_48idm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 6: // addc_48imm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_addc_48imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 7: // and_48idm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_and_48idm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 8: // and_48imm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_and_48imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 9: // bic_48idm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_bic_48idm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 10: // bic_48imm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_bic_48imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 11: // bis_48idm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_bis_48idm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 12: // bis_48imm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_bis_48imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 13: // bit_48idm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_bit_48idm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 14: // bit_48imm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_bit_48imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 15: // cmp_48idm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_cmp_48idm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 16: // cmp_48imm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_cmp_48imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 17: // dadd_48idm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_dadd_48idm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 18: // dadd_48imm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_dadd_48imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 19: // sub_48idm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_sub_48idm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 20: // sub_48imm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_sub_48imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 21: // subc_48idm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_subc_48idm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 22: // subc_48imm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_subc_48imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 23: // xor_48idm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_xor_48idm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 24: // xor_48imm
    isa._behavior_msp430_Double_48(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    isa.behavior_xor_48imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(2), instr_vec->get(3), instr_vec->get(4), instr_vec->get(5), instr_vec->get(6), instr_vec->get(7), instr_vec->get(8));
    break;
   case 25: // mov_32idst
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_mov_32idst(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 26: // mov_32isrc
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_mov_32isrc(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 27: // mov_32imm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_mov_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 28: // mov_32iaim
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_mov_32iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 29: // mov_32irm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_mov_32irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 30: // add_32idst
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_add_32idst(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 31: // add_32isrc
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_add_32isrc(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 32: // add_32imm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_add_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 33: // add_32iaim
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_add_32iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 34: // add_32irm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_add_32irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 35: // addc_32idst
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_addc_32idst(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 36: // addc_32isrc
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_addc_32isrc(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 37: // addc_32imm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_addc_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 38: // addc_32iaim
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_addc_32iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 39: // addc_32irm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_addc_32irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 40: // and_32idst
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_and_32idst(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 41: // and_32isrc
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_and_32isrc(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 42: // and_32imm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_and_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 43: // and_32iaim
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_and_32iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 44: // and_32irm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_and_32irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 45: // bic_32idst
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_bic_32idst(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 46: // bic_32isrc
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_bic_32isrc(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 47: // bic_32imm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_bic_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 48: // bic_32iaim
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_bic_32iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 49: // bic_32irm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_bic_32irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 50: // bis_32idst
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_bis_32idst(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 51: // bis_32isrc
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_bis_32isrc(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 52: // bis_32imm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_bis_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 53: // bis_32iaim
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_bis_32iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 54: // bis_32irm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_bis_32irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 55: // bit_32idst
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_bit_32idst(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 56: // bit_32isrc
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_bit_32isrc(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 57: // bit_32imm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_bit_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 58: // bit_32iaim
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_bit_32iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 59: // bit_32irm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_bit_32irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 60: // cmp_32idst
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_cmp_32idst(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 61: // cmp_32isrc
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_cmp_32isrc(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 62: // cmp_32imm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_cmp_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 63: // cmp_32iaim
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_cmp_32iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 64: // cmp_32irm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_cmp_32irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 65: // dadd_32idst
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_dadd_32idst(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 66: // dadd_32isrc
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_dadd_32isrc(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 67: // dadd_32imm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_dadd_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 68: // dadd_32iaim
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_dadd_32iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 69: // dadd_32irm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_dadd_32irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 70: // sub_32idst
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_sub_32idst(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 71: // sub_32isrc
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_sub_32isrc(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 72: // sub_32imm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_sub_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 73: // sub_32iaim
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_sub_32iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 74: // sub_32irm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_sub_32irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 75: // subc_32idst
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_subc_32idst(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 76: // subc_32isrc
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_subc_32isrc(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 77: // subc_32imm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_subc_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 78: // subc_32iaim
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_subc_32iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 79: // subc_32irm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_subc_32irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 80: // xor_32idst
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_xor_32idst(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 81: // xor_32isrc
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_xor_32isrc(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 82: // xor_32imm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_xor_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 83: // xor_32iaim
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_xor_32iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 84: // xor_32irm
    isa._behavior_msp430_Double_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_xor_32irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(9), instr_vec->get(10), instr_vec->get(11), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 85: // mov_16rm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_mov_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 86: // mov_16irm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_mov_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 87: // mov_16iaim
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_mov_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 88: // add_16rm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_add_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 89: // add_16irm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_add_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 90: // add_16iaim
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_add_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 91: // addc_16rm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_addc_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 92: // addc_16irm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_addc_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 93: // addc_16iaim
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_addc_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 94: // and_16rm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_and_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 95: // and_16irm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_and_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 96: // and_16iaim
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_and_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 97: // bic_16rm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_bic_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 98: // bic_16irm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_bic_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 99: // bic_16iaim
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_bic_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 100: // bis_16rm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_bis_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 101: // bis_16irm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_bis_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 102: // bis_16iaim
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_bis_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 103: // bit_16rm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_bit_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 104: // bit_16irm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_bit_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 105: // bit_16iaim
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_bit_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 106: // cmp_16rm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_cmp_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 107: // cmp_16irm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_cmp_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 108: // cmp_16iaim
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_cmp_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 109: // dadd_16rm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_dadd_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 110: // dadd_16irm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_dadd_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 111: // dadd_16iaim
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_dadd_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 112: // sub_16rm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_sub_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 113: // sub_16irm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_sub_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 114: // sub_16iaim
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_sub_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 115: // subc_16rm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_subc_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 116: // subc_16irm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_subc_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 117: // subc_16iaim
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_subc_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 118: // xor_16rm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_xor_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 119: // xor_16irm
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_xor_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 120: // xor_16iaim
    isa._behavior_msp430_Double(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_xor_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(15), instr_vec->get(16), instr_vec->get(17), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 121: // rrc_32sm
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_rrc_32sm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 122: // rrc_32am
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_rrc_32am(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 123: // rrc_32imm
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_rrc_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 124: // rrc_32im
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_rrc_32im(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 125: // rra_32sm
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_rra_32sm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 126: // rra_32am
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_rra_32am(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 127: // rra_32imm
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_rra_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 128: // rra_32im
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_rra_32im(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 129: // swpb_32sm
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_swpb_32sm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 130: // swpb_32am
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_swpb_32am(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 131: // swpb_32imm
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_swpb_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 132: // swpb_32im
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_swpb_32im(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 133: // sxt_32sm
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_sxt_32sm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 134: // sxt_32am
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_sxt_32am(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 135: // sxt_32imm
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_sxt_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 136: // sxt_32im
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_sxt_32im(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 137: // push_32sm
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_push_32sm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 138: // push_32am
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_push_32am(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 139: // push_32imm
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_push_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 140: // push_32im
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_push_32im(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 141: // call_32sm
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_call_32sm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 142: // call_32am
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_call_32am(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 143: // call_32imm
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_call_32imm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 144: // call_32im
    isa._behavior_msp430_Single_32(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    isa.behavior_call_32im(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(1), instr_vec->get(21), instr_vec->get(22), instr_vec->get(12), instr_vec->get(13), instr_vec->get(14));
    break;
   case 145: // rrc_16rm
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_rrc_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 146: // rrc_16irm
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_rrc_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 147: // rrc_16iaim
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_rrc_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 148: // rra_16rm
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_rra_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 149: // rra_16irm
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_rra_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 150: // rra_16iaim
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_rra_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 151: // swpb_16rm
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_swpb_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 152: // swpb_16irm
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_swpb_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 153: // swpb_16iaim
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_swpb_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 154: // sxt_16rm
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_sxt_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 155: // sxt_16irm
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_sxt_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 156: // sxt_16iaim
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_sxt_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 157: // push_16rm
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_push_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 158: // push_16irm
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_push_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 159: // push_16iaim
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_push_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 160: // call_16rm
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_call_16rm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 161: // call_16irm
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_call_16irm(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 162: // call_16iaim
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_call_16iaim(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 163: // reti
    isa._behavior_msp430_Single(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    isa.behavior_reti(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(23), instr_vec->get(24), instr_vec->get(18), instr_vec->get(19), instr_vec->get(20));
    break;
   case 164: // jne
    isa._behavior_msp430_Jump(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    isa.behavior_jne(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    break;
   case 165: // jeq
    isa._behavior_msp430_Jump(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    isa.behavior_jeq(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    break;
   case 166: // jnc
    isa._behavior_msp430_Jump(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    isa.behavior_jnc(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    break;
   case 167: // jc
    isa._behavior_msp430_Jump(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    isa.behavior_jc(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    break;
   case 168: // jn
    isa._behavior_msp430_Jump(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    isa.behavior_jn(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    break;
   case 169: // jge
    isa._behavior_msp430_Jump(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    isa.behavior_jge(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    break;
   case 170: // jl
    isa._behavior_msp430_Jump(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    isa.behavior_jl(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    break;
   case 171: // jmp
    isa._behavior_msp430_Jump(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    isa.behavior_jmp(static_cast<msp430_parms::ac_stage_list>(id), 0, instr_vec->get(25), instr_vec->get(26), instr_vec->get(27));
    break;
  }
 }
 delete instr_vec;
 done.notify();
 return;
}
