/******************************************************
 * Stage Module Implementation File.                  *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "pipe_EX.H"

void AC_pipe_EX::pipe_EX::behavior() {

  ac_instruction *instr, *format;
  unsigned ins_id;
  ac_instr *instr_vec;

  instr_vec = new ac_instr(regin.read());

  ins_id = instr_vec->get(IDENT);
  if( ins_id != 0 ) {
    instr = (ac_instruction *)ISA.instr_table[instr_vec->get(IDENT)][1];
    format = (ac_instruction *)ISA.instr_table[ins_id][2];
    format->set_fields( *instr_vec  );
    instr->set_fields( *instr_vec  );
    ISA.instruction.behavior( (ac_stage_list)id );
    format->behavior( (ac_stage_list)id );
    instr->behavior( (ac_stage_list)id );
  }
  delete instr_vec;
  bhv_done.write(1);
}

